export type Permission =
  | 'dashboard:read'
  | 'orders:read'
  | 'orders:write'
  | 'catalog:read'
  | 'catalog:write'
  | 'team:read'
  | 'team:manage'
  | 'users:read'
  | 'users:create'
  | 'users:update'
  | 'settings:read'
  | 'settings:admin'
  | 'qualifications:read'
  | 'qualifications:create'
  | 'qualifications:delete'
  | 'schedules:read'
  | 'schedules:write';
